-- MySQL Script generated by MySQL Workbench
-- Sun Jul  6 21:47:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiendaMonica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendaMonica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendaMonica` DEFAULT CHARACTER SET utf8 ;
USE `tiendaMonica` ;

-- -----------------------------------------------------
-- Table `tiendaMonica`.`enlace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`enlace` (
  `idEnlace` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(200) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idEnlace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `nombreCliente` VARCHAR(100) NOT NULL,
  `apellidoCliente` VARCHAR(100) NOT NULL,
  `fechaPedido` DATETIME NOT NULL,
  `idProducto` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `diseño` VARCHAR(200) NULL,
  `observaciones` VARCHAR(200) NULL,
  `estado` TINYINT NOT NULL,
  `idEnlace` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_pedido_enlace1_idx` (`idEnlace` ASC),
  CONSTRAINT `fk_pedido_enlace1`
    FOREIGN KEY (`idEnlace`)
    REFERENCES `tiendaMonica`.`enlace` (`idEnlace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `rol` INT NOT NULL,
  `correo` VARCHAR(100) NOT NULL UNIQUE,
  `contraseña` VARCHAR(200) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`provedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`provedores` (
  `idProvedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contacto` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idProvedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`provedores_has_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`provedores_has_categorias` (
  `idProvedor` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProvedor`, `idCategoria`),
  INDEX `fk_provedores_has_categorias_categorias1_idx` (`idCategoria` ASC),
  INDEX `fk_provedores_has_categorias_provedores_idx` (`idProvedor` ASC),
  CONSTRAINT `fk_provedores_has_categorias_provedores`
    FOREIGN KEY (`idProvedor`)
    REFERENCES `tiendaMonica`.`provedores` (`idProvedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provedores_has_categorias_categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `tiendaMonica`.`categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`compras` (
  `idCompras` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `cantidad` INT NOT NULL,
  `costo` DECIMAL(18,2) NOT NULL,
  `idUsuario` INT NOT NULL,
  `idProvedor` INT NOT NULL,
  PRIMARY KEY (`idCompras`),
  INDEX `fk_compras_usuarios1_idx` (`idUsuario` ASC),
  INDEX `fk_compras_provedores1_idx` (`idProvedor` ASC),
  CONSTRAINT `fk_compras_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tiendaMonica`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_provedores1`
    FOREIGN KEY (`idProvedor`)
    REFERENCES `tiendaMonica`.`provedores` (`idProvedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`tipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`tipoProducto` (
  `idTipoProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idTipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `stock` INT NOT NULL,
  `precio` DECIMAL(18,2) NOT NULL,
  `estado` TINYINT NOT NULL,
  `idProvedor` INT NOT NULL,
  `idTipoProducto` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_productos_provedores1_idx` (`idProvedor` ASC),
  INDEX `fk_productos_tipoProducto1_idx` (`idTipoProducto` ASC),
  CONSTRAINT `fk_productos_provedores1`
    FOREIGN KEY (`idProvedor`)
    REFERENCES `tiendaMonica`.`provedores` (`idProvedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_tipoProducto1`
    FOREIGN KEY (`idTipoProducto`)
    REFERENCES `tiendaMonica`.`tipoProducto` (`idTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`productos_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`productos_has_pedido` (
  `idProducto` INT NOT NULL,
  `idPedido` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `idPedido`),
  INDEX `fk_productos_has_pedido_pedido1_idx` (`idPedido` ASC),
  INDEX `fk_productos_has_pedido_productos1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_productos_has_pedido_productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `tiendaMonica`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_pedido_pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `tiendaMonica`.`pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`pagos` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(18,2) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `estado` TINYINT NULL,
  `idCompra` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_pagos_compras1_idx` (`idCompra` ASC),
  CONSTRAINT `fk_pagos_compras1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `tiendaMonica`.`compras` (`idCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`entregas` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `fechaLlegada` DATETIME NULL,
  `descripcion` VARCHAR(200) NULL,
  `estadoEntrega` TINYINT NULL,
  `idCompra` INT NOT NULL,
  PRIMARY KEY (`idEntrega`),
  INDEX `fk_entregas_compras1_idx` (`idCompra` ASC),
  CONSTRAINT `fk_entregas_compras1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `tiendaMonica`.`compras` (`idCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`insumos` (
  `idInsumo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `cantidad` INT NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idInsumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`insumos_has_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`insumos_has_productos` (
  `idInsumo` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idInsumo`, `idProducto`),
  INDEX `fk_insumos_has_productos_productos1_idx` (`idProducto` ASC),
  INDEX `fk_insumos_has_productos_insumos1_idx` (`idInsumo` ASC),
  CONSTRAINT `fk_insumos_has_productos_insumos1`
    FOREIGN KEY (`idInsumo`)
    REFERENCES `tiendaMonica`.`insumos` (`idInsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_insumos_has_productos_productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `tiendaMonica`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`ventas` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `total` DECIMAL(18,2) NOT NULL,
  `estadoPago` TINYINT NOT NULL,
  `estadoVenta` TINYINT NOT NULL,
  `ganancias` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`idVenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaMonica`.`ventas_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaMonica`.`ventas_has_pedido` (
  `idVenta` INT NOT NULL,
  `idPedido` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precioUnitario` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`idVenta`, `idPedido`),
  INDEX `fk_ventas_has_pedido_pedido1_idx` (`idPedido` ASC),
  INDEX `fk_ventas_has_pedido_ventas1_idx` (`idVenta` ASC),
  CONSTRAINT `fk_ventas_has_pedido_ventas1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `tiendaMonica`.`ventas` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_has_pedido_pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `tiendaMonica`.`pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
